[2025-08-13T21:22:12.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-13T21:22:12.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_extra_create_and_log.create_table manual__2025-08-13T21:22:11.382007+00:00 [queued]>
[2025-08-13T21:22:12.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_extra_create_and_log.create_table manual__2025-08-13T21:22:11.382007+00:00 [queued]>
[2025-08-13T21:22:12.361+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-13T21:22:12.365+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_table> on 2025-08-13 21:22:11.382007+00:00
[2025-08-13T21:22:12.367+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-13T21:22:12.367+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2025-08-13T21:22:12.368+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_extra_create_and_log', 'create_table', 'manual__2025-08-13T21:22:11.382007+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8k5cyj3x']
[2025-08-13T21:22:12.368+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask create_table
[2025-08-13T21:22:12.386+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_extra_create_and_log.create_table manual__2025-08-13T21:22:11.382007+00:00 [running]> on host 1ed929767bb5
[2025-08-13T21:22:12.413+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_extra_create_and_log' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T21:22:11.382007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T21:22:11.382007+00:00'
[2025-08-13T21:22:12.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-13T21:22:12.421+0000] {base.py:84} INFO - Using connection ID 'pg_extra_conn' for task execution.
[2025-08-13T21:22:12.432+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-13T21:22:12.433+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-13T21:22:12.436+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pg_extra_create_and_log, task_id=create_table, run_id=manual__2025-08-13T21:22:11.382007+00:00, execution_date=20250813T212211, start_date=20250813T212212, end_date=20250813T212212
[2025-08-13T21:22:12.465+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-13T21:22:12.474+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-13T21:22:12.474+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
