[2025-08-13T21:22:14.212+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-13T21:22:14.219+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-13T21:22:11.382007+00:00 [queued]>
[2025-08-13T21:22:14.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-13T21:22:11.382007+00:00 [queued]>
[2025-08-13T21:22:14.222+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-13T21:22:14.225+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_data> on 2025-08-13 21:22:11.382007+00:00
[2025-08-13T21:22:14.227+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-13T21:22:14.227+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2025-08-13T21:22:14.228+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_extra_create_and_log', 'log_data', 'manual__2025-08-13T21:22:11.382007+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpr5yamwdt']
[2025-08-13T21:22:14.228+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask log_data
[2025-08-13T21:22:14.241+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-13T21:22:11.382007+00:00 [running]> on host 1ed929767bb5
[2025-08-13T21:22:14.263+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_extra_create_and_log' AIRFLOW_CTX_TASK_ID='log_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T21:22:11.382007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T21:22:11.382007+00:00'
[2025-08-13T21:22:14.263+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-13T21:22:14.269+0000] {base.py:84} INFO - Using connection ID 'pg_extra_conn' for task execution.
[2025-08-13T21:22:14.271+0000] {logging_mixin.py:188} INFO - Содержимое таблицы sample_data:
[2025-08-13T21:22:14.271+0000] {logging_mixin.py:188} INFO - (1, 'alpha', 10)
[2025-08-13T21:22:14.271+0000] {logging_mixin.py:188} INFO - (2, 'beta', 20)
[2025-08-13T21:22:14.271+0000] {logging_mixin.py:188} INFO - (3, 'gamma', 30)
[2025-08-13T21:22:14.271+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-13T21:22:14.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-13T21:22:14.274+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pg_extra_create_and_log, task_id=log_data, run_id=manual__2025-08-13T21:22:11.382007+00:00, execution_date=20250813T212211, start_date=20250813T212214, end_date=20250813T212214
[2025-08-13T21:22:14.286+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-13T21:22:14.291+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-13T21:22:14.291+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
